"""
Django settings for eventdiary project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.core.exceptions import ImproperlyConfigured
import cloudinary

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
 
def get_env_variable(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = "Set the %s environment variable" % var_name
        raise ImproperlyConfigured(error_msg)

# # SECURITY WARNING: keep the secret key used in production secret!
import envvars
envvars.load()
SECRET_KEY = envvars.get('SECRET_KEY')

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',
    'bootstrap3',
    'cloudinary',
    'envvars',
    'fancybox',
    'multiselectfield',
    'phonenumber_field',
    'smart_selects',
    'widget_tweaks',
    'web.accounts',
    'web.deals',
    'web.authentication',
    'web.centers',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

# AUTH_USER_MODEL = 'accounts.UserProfile'

ROOT_URLCONF = 'eventdiary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventdiary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'theeventdiary',
        'USER': 'theeventdiary',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '',
    }
}

import dj_database_url

DATABASES["default"] = dj_database_url.config()

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ANYMAIL = {
#     "MAILGUN_API_KEY": envvars.get('ACCESS_KEY'),
#     "MAILGUN_SENDER_DOMAIN": envvars.get('SENDER_DOMAIN'),
#     "MAILGUN_PUBLIC_KEY": envvars.get('MAILGUN_PUB_KEY'),
#     "MAILGUN_SMTP_LOGIN": envvars.get('MAILGUN_SMTP_LOGIN'),
#     "MAILGUN_SMTP_PASSWORD": envvars.get('MAILGUN_SMTP_PASSWORD'),
#     "MAILGUN_SMTP_PORT": 587,
#     "MAILGUN_SMTP_SERVER": envvars.get('MAILGUN_SMTP_SERVER'),
#     "MAILGUN_SEND_DEFAULTS":{
#         "esp_extra": {"sender_domain": "mail.theeventdiary.com"}
#     }
# }

# EMAIL_BACKEND = "anymail.backends.mailgun.MailgunBackend"
# DEFAULT_FROM_EMAIL = "info@theeventdiary.com"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = envvars.get('EMAIL_HOST')
EMAIL_HOST_USER = envvars.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = envvars.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = "staticfiles"

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

cloudinary.config(
  cloud_name = "theeventdiary",
  api_key = "717232858138761",
  api_secret = "P7ypHvEjMKDrc4OcLWfNSbo7mY4"
)
