# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_auto_20170111_1550'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='user_centers',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='centers.Center'),
            preserve_default=False,
        ),
    ]
