# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_merchant_user_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='user_centers',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='centers.Center'),
        ),
    ]
