# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 22:02
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_libs.models_mixins
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            bases=(django_libs.models_mixins.TranslationModelMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatusTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='centers.BookingStatus')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'centers_bookingstatus_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=b'')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default=b'', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_modified', models.DateField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default=b'http://res.cloudinary.com/theeventdiary/image/upload/v1483614044/lg_m8sc17.jpg', max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gov', models.SmallIntegerField(choices=[(1, b'Abule Ijesha'), (2, b'Abule egba'), (3, b'Alagbado'), (4, b'Akowonjo'), (5, b'Baruwa'), (6, b'Dopemu'), (7, b'Egbe'), (8, b'Egbeda'), (9, b'Ejigbo'), (10, b'Ijegun'), (11, b'Ikotun'), (12, b'Egan'), (13, b'Iyana Ipaja'), (14, b'Ipaja'), (15, b'Jakande'), (16, b'Ojo'), (17, b'Ojota'), (18, b'Idimu'), (19, b'Adeniyi jones'), (20, b'Agbara'), (21, b'Agege'), (22, b'Agidingbi'), (23, b'Agric'), (24, b'Aguda'), (25, b'Airport road'), (26, b'Ajah'), (27, b'Ajao estate'), (28, b'Ajeromi-Ajegunle'), (29, b'Ajeromi-Ifelodun'), (30, b'Akessan Estate'), (31, b'Akoka'), (32, b'Akute-Ajuwon'), (33, b'Alausa'), (34, b'Alimosho'), (35, b'Allen'), (36, b'Amuwo-odofin'), (37, b'Anthony'), (38, b'Apapa'), (39, b'Apapa-Ajegunle'), (40, b'Awolowo'), (41, b'Awolowo way'), (42, b'Badagry'), (43, b'Banana-Island'), (44, b'Bariga'), (45, b'Bode Thomas'), (46, b'Bourdillon'), (47, b'Chisco'), (48, b'Constain-Ijora Olopa')], default=33)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.SmallIntegerField(choices=[(1, b'Abia'), (2, b'Abuja'), (3, b'Adamawa'), (4, b'Akwa Ibom'), (5, b'Anambra'), (6, b'Bauchi'), (7, b'Bayelsa'), (8, b'Benue'), (9, b'Borno'), (10, b'Cross River'), (11, b'Delta'), (12, b'Ebonyi'), (13, b'Edo'), (14, b'Ekiti'), (15, b'Enugu'), (16, b'Gombe'), (17, b'Imo'), (18, b'Jigawa'), (19, b'Kaduna'), (20, b'Kano'), (21, b'Katsina'), (22, b'Kebbi'), (23, b'Kogi'), (24, b'Kwara'), (25, b'Lagos'), (26, b'Nassarawa'), (27, b'Niger'), (28, b'Ogun'), (29, b'Ondo'), (30, b'Osun'), (31, b'Oyo'), (32, b'Plateau'), (33, b'Rivers'), (34, b'Sokoto'), (35, b'Taraba'), (36, b'Yobe'), (37, b'Zamfara')], default=25)),
            ],
        ),
        migrations.AddField(
            model_name='localgovarea',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_lga', to='centers.State'),
        ),
        migrations.AddField(
            model_name='center',
            name='lga',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'state', chained_model_field=b'state', default=1, on_delete=django.db.models.deletion.CASCADE, to='centers.LocalGovArea'),
        ),
        migrations.AddField(
            model_name='center',
            name='state',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='center_state', to='centers.State'),
        ),
        migrations.AddField(
            model_name='booking',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingstatustranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
