# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 23:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localgovarea',
            old_name='state_name',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='center',
            name='lga',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=b'state', chained_model_field=b'state', on_delete=django.db.models.deletion.CASCADE, to='centers.LocalGovArea'),
        ),
    ]
