# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:08
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20161025_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=b'img/test-run-gb.jpeg', max_length=255),
        ),
    ]
