# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_auto_20170109_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_state', to='centers.State'),
        ),
        migrations.AlterField(
            model_name='localgovarea',
            name='local_gov',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
