# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_auto_20161209_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='owner',
        ),
    ]
