# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_remove_center_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
