# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_auto_20161217_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
    ]
