# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_auto_20170110_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='capacity',
            new_name='banquet_arrangement',
        ),
        migrations.AddField(
            model_name='center',
            name='center_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Multipurpose hall'), (2, b'Garden'), (3, b'Conference centre'), (4, b'Auditorium'), (5, b'Field'), (6, b'Pool Side'), (7, b'Open side'), (8, b'Hotel event hall'), (9, b'Club hall'), (10, b'Marquee')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='facility',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Tables'), (2, b'Chairs'), (3, b'Changing Room'), (4, b'Power Supply'), (5, b'Parking Space'), (6, b'Air Conditioner'), (7, b'Television'), (8, b'Security'), (9, b'Sound System'), (10, b'Projector'), (9, b'Pulpit'), (10, b'Writing Board'), (9, b'Rest Room'), (10, b'Fan'), (9, b'Stage'), (10, b'Staging Light'), (9, b'Cold Room'), (10, b'Traffic controllers')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='center',
            name='policy',
            field=models.TextField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='center',
            name='theatre_arrangement',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
