# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 10:32
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_center_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=b'image'),
        ),
    ]
