# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 10:42
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0010_auto_20170104_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=b'../../staticfiles/img/lg.jpg', max_length=255),
        ),
    ]
