# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 11:02
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_auto_20170105_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=b'http://res.cloudinary.com/theeventdiary/image/upload/v1483614044/lg_m8sc17.jpg', max_length=255),
        ),
    ]
