# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_auto_20170111_1550'),
        ('accounts', '0002_userprofile_is_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=b'', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_location_state', to='centers.State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(default=b'', max_length=20, null=True),
        ),
    ]
