# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170228_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='location',
        ),
    ]
